POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "radish",
    "number": "1234-23434"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "carrot"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "1234-23434"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
}